#!/bin/bash
#PBS -q qexp
#PBS -A DD-22-68
#PBS -l select=1:ncpus=36 
#PBS -l walltime=0:45:00
#PBS -m e
#PBS -N AVS-evaluate


cd $PBS_O_WORKDIR
ml intel-compilers/2022.1.0 CMake/3.23.1-GCCcore-11.3.0 # pouze na Barbore


[ -d build_evaluate ] && rm -rf build_evaluate
[ -d build_evaluate ] || mkdir build_evaluate

cd build_evaluate
rm tmp_*

CC=icc CXX=icpc cmake ..
make

ml matplotlib/3.5.2-foss-2022a
bash ../scripts/generate_data_and_plots.sh